### ISSUE TITLE
work out a way to activate only one toolbox instance on new modmail.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#1]
"Old" and new toolbox will be running side by side and this is fine when confronted for most of the website as the old one will only activate on the old tech stack and the new one only on the new one. With the exception of new modmail. 

Ideally when both toolbox versions are installed the new one will handle new modmail, but this requires the old one to not activate.  I am thinking of getting the new toolbox version to write a key to localstorage on activation which can be used by old toolbox as an indicator to simply not activate. An alternative would simply be a class on the body. 

This obviously requires a change in the old toolbox codebase as well. It needs to hold of activating on new modmail for a little bit in order to make it so V4 has already written the needed info.

**Comment by Geo1088** [comment]
@creesch is this already done or does it need more work?

**Comment by creesch** [comment]
Keep it open for now, race conditions do cause some issues at times. I am wondering if we should make it work both ways so we can be fairly sure no toolbox is ever active the same time.

**Comment by creesch** [comment]
This was fixed by using session storage instead of a class added to the body.
