### ISSUE TITLE
General CSS issues

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#10]
_From @Geo1088 on August 23, 2017 14:17_

Biggest visible issue with the style now is the new site relies on `box-sizing: border-box;` a lot, and toolbox's elements all assume `box-sizing: content-box;` instead. In general things need to be updated to adapt to the new CSS.

_Copied from original issue: Geo1088/reddit-moderator-toolbox#5_

**Comment by creesch** [comment]
Yup, if manageable I want to take this moment to clean up properly anyway.

**Comment by creesch** [comment]
Some other things are input elements. Reddit shows them without borders now.

**Comment by creesch** [comment]
_From @Geo1088 on August 23, 2017 14:44_

Yeah, that annoys me. Not sure why that's a thing, but it's still easily overcome.

**Comment by creesch** [comment]
Assigned @Geo1088 as you are effectively working on most of these anyway. So nothing actually changed.

**Comment by Geo1088** [comment]
Context popup for comments seems borked.
![image](https://user-images.githubusercontent.com/4165301/58756593-7d7abf00-84c9-11e9-9483-c3af7233e93d.png)

**Comment by creesch** [comment]
I don't see any borkage here...

**Comment by creesch** [comment]
ALready said it on discord, but for clarity. I meant that I can't reproduce what is visible in the screenshot.

**Comment by Geo1088** [comment]
Above issue is calused by a CSS conflict between old and new Toolbox (rule not prefixed with `.mod-toolbox` in v3). @creesch should we make a v3 issue for stuff like this? I'm sure there's more that we need to audit.

**Comment by creesch** [comment]
I don't think so, once we are over to v5 this isn't all that relevant anymore. So if we find some we can fix it but I don't think it needs more actual effort.

**Comment by Geo1088** [comment]
Releasing soon and there's nothing specific to work on here so closing this now.
