### ISSUE TITLE
Some users experience errors with certain api related actions.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#2]
- https://www.reddit.com/r/tb_redesign/comments/7yjquv/how_to_fix_the_save_failed_error_on_chrome/
- Also possibly related  

  - https://www.reddit.com/r/tb_redesign/comments/7px07y/error_trying_to_ban_user_from_mod_tools_button/  
  - https://www.reddit.com/r/tb_redesign/comments/7y45hz/unable_to_ban_users_using_toolbox/  
  - https://www.reddit.com/r/tb_redesign/comments/7px07y/error_trying_to_ban_user_from_mod_tools_button/

Have not been able to reproduce but suspect it might have to do with permanently being opted in.

**Comment by diceroll123** [comment]
I was going to tack this into #5 but I'll say here: adding removal reasons manually (as in, going into the thread and pressing the "add removal reason" button) doesn't work when I'm not on alpha.reddit.com, it's just 403 error for api/flair and api/comment.

**Comment by creesch** [comment]
should be solve with bba47a5c18c116a1b53180a0ef4aa00609d51f8e
