### ISSUE TITLE
Usernotes are applied to all users in a conversation

### ISSUE THREAD

**Issue by jackson1442** [toolbox-team/reddit-moderator-toolbox-redesign#22]
<img width="660" alt="screen shot 2018-04-11 at 7 32 27 pm" src="https://user-images.githubusercontent.com/20214768/38650086-9d46592c-3dbf-11e8-9812-d66f098ffef1.png">

I have *not* tried to reproduce this, but this seems like a weird error. 

Toolbox v4.0.15 (beta) "new narwhal"  
Chrome v65.0.3325.181 on macOS

**Comment by creesch** [comment]
Cannot reproduce
