### ISSUE TITLE
Changing queue-sort with groupCommentsOnModPage causes hr-tags to appear bottom of the page

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox-redesign#24]
When you have queuetools, `groupCommentsOnModPage` setting enabled and you change the sort within a queue, the hr lines will be moved to the bottom of the page.

1. Enable [`groupCommentsOnModPage`](https://www.reddit.com/#?tbsettings=queuetools&setting=groupcommentsonmodpage)
1. Go to unmoderated or modqueue
1. Change the sort to one that changes the order
1. Scroll to the bottom and observe a stack of `<hr>`-elements

**Comment by Geo1088** [comment]
This is actually an issue only on the old.reddit repo, as this function isn't a thing on the redesign. Regardless, fixed in https://github.com/toolbox-team/reddit-moderator-toolbox/commit/4d9ef8bec0c4b9f4ad220a8c3057d8f2fe92b9a3.
