### ISSUE TITLE
Rewrite build process

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#26]
What the title says, gulp modules are maintained poorly and it is overly complicated to do it through the gulp flow while we only do some fairly basic stuff anyway. 

Seems to me that a simple npm script is easier to maintain.

**Comment by creesch** [comment]
Changed the title, effectively we only need to zip for building as the edge process will also move to that. 

Extra todo: 

- [ ] Automated submissions to stores

**Comment by Geo1088** [comment]
Fixed in c1334d34018048eb78eda30c3e82d88360aa58c2
