### ISSUE TITLE
Make sure that tabs created from a notification open in the active (foreground window).

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#29]
https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/blob/master/extension/data/background/background.js#L54

It would be annoying if it decides to open the tab in a background window.

**Comment by Geo1088** [comment]
Would this be accomplished via something like this?

```
chrome.windows.getLastFocused(window => {
	chrome.tabs.create({
		url: '...',
		windowId: window.id,
	});
});
```

https://developer.chrome.com/extensions/windows#method-getLastFocused

**Comment by creesch** [comment]
probably yeah.
