### ISSUE TITLE
Modqueue notifications from new modmail link to wrong domain

### ISSUE THREAD

**Issue by leviroth** [toolbox-team/reddit-moderator-toolbox-redesign#41]
To reproduce:

1. Have the new modmail as your only reddit tab open
2. Wait for, or generate, a new modqueue item
3. Click the "New modqueue item" notification
4. The link goes to https://mod.reddit.com/r/mod/about/modqueue, which is a 404 error.

I found this on Firefox. I don't know if it applies to other kinds of notification.

**Comment by Geo1088** [comment]
I feel like the proper solution to this would just be moving notifications entirely to the background page. That seems like a fair amount of work though. @creesch, can you think of an easier temporary solution for 4.0.18?

**Comment by creesch** [comment]
I don't think this is actually an issue anymore as this issue was opened before I rewrote notifications. We'd need to test this.

**Comment by Geo1088** [comment]
Confirmed fixed on b07ed1ed677bc7ed0b276c97486df15c7bd57921
