### ISSUE TITLE
Implement context menu in pure CSS (also other stuff)

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox-redesign#42]
Annoying me because it opens up on page load and takes a second to collapse. The show/hide behavior can be done just with CSS transitions, so I'll look into doing it that way.

Also, on a slightly related note, there should be no left border on that menu since it butts up against the left side of the screen. It and the modbar handle should also be the same size as the bottombar handle when collapsed, preferably.

**Comment by Geo1088** [comment]
After reviewing the code i noticed that the annoying part is actually intentional, which makes sense. Can still be redone to not rely on jQuery assigning classes, though.

**Comment by creesch** [comment]
Yeah the annoying part is there to make people aware there is a menu there as they otherwise would not see it at all and we'd get a ton of support questions.

**Comment by Geo1088** [comment]
Closing because I'm dumb and this doesn't actually need to be changed
