### ISSUE TITLE
Fix new modmail counter for upcoming chrome version. 

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#43]
[this breaks the counter](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches). Luckily the solution is simple, move the request to a background page. I simply need to implement this.

**Comment by Geo1088** [comment]
Fixed with fed4d0e63fdf86357e3da4d0a4985ba66c6411ae in addition to all other cases where this change breaks things
