### ISSUE TITLE
Issues with links to Reddit pages

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox-redesign#47]
Generally, relative links (e.g. `<a href="/r/toolbox">`) work fine for linking to places on Reddit from within the extension. However, if we're on mod.reddit.com, none of those redirects work, so we can't make a link for that. We need to standardize the usage of relative links in the extension so things don't break on mod.reddit.com but still respect the user's subdomain otherwise.

Brainstorm: maybe we could add a utility function for it like this?

```js
TBUtils.link = relativeURL => TBUtils.isNewModmail ? `https://www.reddit.com${relativeURL}` : relativeURL;
// called like:
$(`<a href="${TBUtils.link('/r/toolbox/about/modqueue')}">`)
```

**Comment by creesch** [comment]
Looks like an elegant solution to me.
