### ISSUE TITLE
Things missing in 'old' reddit backport we might want to put in.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#48]
Stuff that v3 of toolbox offers but v4 does currently not. 

- [ ] "add removal reason" button. 
- [ ] toolbox settings in the sidebar mod sections (not sure if we want to add those back).

A bunch more I am now forgetting but keep thinking we should add back.

**Comment by Geo1088** [comment]
Decided to close this after da31848 since I think it's better that we keep Toolbox stuff in the context menu and avoid injecting stuff into the DOM where we can for clarity. Further backports can get their own issues as they come up.
