### ISSUE TITLE
Make sure legacy/old reddit functionality has the same settings keys as v3

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox-redesign#49]
We should be mostly good here as the new modules have the same name and we made the functionality to drop in legacy code specifcally for old reddit. What we need to do is check if any functionality is currently missing. 

This issue is just here to make sure that gets done.

**Comment by creesch** [comment]
Are we missing old reddit functionality actually? (besides the stuff we explicitly dropped).

**Comment by Geo1088** [comment]
Pretty sure this is all good. Only issue I knew of was fixed (#48, da31848) and the thing is being released now so if anything else comes up we can make new, more specific issues.
