### ISSUE TITLE
Removal reasons doesn't automatically pop up after removing a thread

### ISSUE THREAD

**Issue by diceroll123** [toolbox-team/reddit-moderator-toolbox-redesign#5]
I remove a thread, and that's it, the thread gets removed. It should pop the removal dialog up, but for now I have to go into the thread manually and add the removal reason through a comment using the "add a removal reason" button.

Hopefully I'm not missing a setting here that makes that happen.

**Comment by creesch** [comment]
Thank you for reporting this, though next time post it to /r/tb_redesign first.

**Comment by creesch** [comment]
This has been fixed in the latest release.
