### ISSUE TITLE
Apply fix for nuke button in other languages

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox-redesign#52]
do this thing https://github.com/toolbox-team/reddit-moderator-toolbox/commit/522685962278c91047a1c2406bfc58684040ace3

**Comment by creesch** [comment]
Should not be needed as we use redesign nuke which doesn't use dom traversing.

**Comment by Geo1088** [comment]
Oh, you're right, mb
