### ISSUE TITLE
Subreddit configuration unavailable if /w/toolbox doesn't exist

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox-redesign#67]
Observed behaviors:

- On a freshly created subreddit, the context menu doesn't exist and there's no way to interact with subreddit-specific settings.
- On a subreddit with a `/w/usernotes` but no `/w/toolbox`, the context menu exists and the usernotes kinda(?) work, but the "/r/\<sub> config" button does nothing at all.

**Comment by creesch** [comment]
> On a freshly created subreddit, the context menu doesn't exist 

That is likely just toolbox cache. 

Clearing it will make the button show up. I can confirm that with no existing config it appears to be currently broken.
