### ISSUE TITLE
Sub context menu doesn't show up on wiki pages

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox-redesign#68]

**Comment by creesch** [comment]
Needs to be added in this section: https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/blob/master/extension/data/tbutils.js#L2906-L3049

We also probably want to add two types of unknown here: https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/blob/master/extension/data/tbutils.js#L3034 

1. for urls that at least match `/r/subreddit/something` so we can always fill in the subreddit bit (we'd need to exclude some fake subreddits though like `/r/mod` and such)
2. The current unknown we already have.
